# Generated by Django 5.2.8 on 2025-11-23 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.TextField(max_length=255)),
                ('modelo', models.TextField(max_length=255)),
                ('ano', models.IntegerField()),
                ('km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telefone_contato', models.CharField(max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos/')),
                ('ordem', models.IntegerField(blank=True, editable=False, null=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='anuncios.anuncio')),
            ],
        ),
    ]
